CREATE TABLE IF NOT EXISTS player_statistics (
    player_name VARCHAR(16) PRIMARY KEY,
    blocks_broken INT NOT NULL DEFAULT 0,
    blocks_placed INT NOT NULL DEFAULT 0,
    mobs_killed INT NOT NULL DEFAULT 0,
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
