# MySQL 数据库配置
database:
  host: "localhost"
  port: 3306
  name: "minecraft_stats"
  username: "mc_stats"
  password: "secure_password_123"
  use_ssl: false
  auto_reconnect: true

# Redis 缓存配置
redis:
  host: "localhost"
  port: 6379
  password: ""        # 若未设置密码，请留空或删除字段
  database: 0         # Redis 默认 db 0
  timeout_ms: 2000    # 连接超时时间
  # 连接池配置
  max_total: 20       # 最大连接数
  max_idle: 10       # 最大空闲连接数
  min_idle: 2         # 最小空闲连接数
  max_wait_ms: 3000   # 获取连接最大等待时间
  test_on_borrow: true    # 获取连接时测试有效性
  test_on_return: true    # 归还连接时测试有效性
  test_while_idle: true   # 空闲时测试连接

# 插件运行参数
debug: false
auto_save_interval_minutes: 2   # 自动将 Redis 数据同步到 MySQL 的间隔
